(define (domain sokoban-sequential)
(:requirements :typing)
(:types thing location direction - object player stone - thing)
(:predicates (clear ?l - location)
(at ?t - thing ?l - location)
(at-goal ?s - stone)
(is-goal ?l - location)
(is-nongoal ?l - location)
(move-dir ?from - location ?to - location ?dir - direction))
(:action move
:parameters (?p - player ?from - location ?to - location ?dir - direction)
:precondition (and (move-dir ?from ?to ?dir)
(clear ?to)
(at ?p ?from))
:effect (and (clear ?from)
(is-nongoal ?to)
(is-nongoal ?from)
(at ?p ?to)
(not (at ?p ?from))
(not (clear ?to)))
)
(:action push-to-nongoal
:parameters (?p - player ?s - stone ?ppos - location ?from - location ?to - location ?dir - direction)
:precondition (and (is-nongoal ?ppos)
(at ?p ?to)
(at ?s ?ppos)
(at ?p ?from)
(move-dir ?from ?ppos ?dir)
(is-goal ?ppos)
(move-dir ?to ?to ?dir)
(is-nongoal ?from)
(clear ?from)
(at ?s ?from)
(is-nongoal ?to)
(at ?s ?to))
:effect (and (at-goal ?s)
(move-dir ?ppos ?to ?dir)
(move-dir ?to ?ppos ?dir)
(move-dir ?from ?to ?dir)
(move-dir ?to ?from ?dir)
(is-goal ?from)
(clear ?to)
(clear ?ppos)
(move-dir ?from ?from ?dir)
(at ?p ?ppos)
(not (at ?p ?to))
(not (is-goal ?ppos))
(not (is-nongoal ?to))
(not (at ?s ?to)))
)
(:action push-to-goal
:parameters (?p - player ?s - stone ?ppos - location ?from - location ?to - location ?dir - direction)
:precondition (and (clear ?to)
(is-goal ?to)
(is-nongoal ?from)
(at ?p ?ppos)
(at ?s ?from))
:effect (and (at-goal ?s)
(at ?p ?from)
(clear ?ppos)
(at ?s ?to)
(not (clear ?to))
(not (at ?p ?ppos))
(not (at ?s ?from)))
)
)