(define (domain sokoban-sequential)
  (:requirements :typing)
  (:types thing location direction - object player stone - thing)
  (:predicates (clear ?l - location)
               (at ?t - thing ?l - location)
               (at-goal ?s - stone)
               (is-goal ?l - location)
               (is-nongoal ?l - location)
               (move-dir ?from - location ?to - location ?dir - direction))
  (:action move
           :parameters (?p - player ?from - location ?to - location ?dir - direction)
           :precondition (and (clear ?to)
                              (at ?p ?from)
                              (is-nongoal ?from))
           :effect (and (clear ?from)
                        (is-nongoal ?to)
                        (at ?p ?to)
                        (not (clear ?to))
                        (not (at ?p ?from)))
           )
  (:action push-to-nongoal
           :parameters (?p - player ?s - stone ?ppos - location ?from - location ?to - location ?dir - direction)
           :precondition (and (clear ?to)
                              (move-dir ?ppos ?from ?dir)
                              (at ?s ?from)
                              (is-nongoal ?from)
                              (at ?p ?ppos)
                              (move-dir ?from ?to ?dir))
           :effect (and (at ?s ?to)
                        (clear ?ppos)
                        (at ?p ?from)
                        (not (clear ?to))
                        (not (at ?s ?from))
                        (not (at ?p ?ppos)))
           )
  (:action push-to-goal
           :parameters (?p - player ?s - stone ?ppos - location ?from - location ?to - location ?dir - direction)
           :precondition (and (clear ?to)
                              (at ?s ?from)
                              (is-nongoal ?ppos)
                              (at ?p ?ppos)
                              (is-goal ?to))
           :effect (and (at ?s ?to)
                        (clear ?ppos)
                        (move-dir ?ppos ?from ?dir)
                        (at ?p ?from)
                        (is-nongoal ?from)
                        (at-goal ?s)
                        (not (clear ?to))
                        (not (at ?s ?from))
                        (not (at ?p ?ppos)))
           )
  )
